### ISSUE TITLE
Search bar has disappeared

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hub/ACCESS-Hub#78] opened 2022-09-17 01:44 UTC
The search bar seems to have disappeared from the headers of both "sites".

**Comment by ccarouge** [comment] 2022-09-19 01:51
The addition of the git-revision-date-localized plugin caused this. Looking to see why it is happening.

**Comment by ccarouge** [comment] 2022-09-19 01:53
Found the cause in the Material for Mkdocs documentation:
> The built-in search plugin integrates seamlessly with Material for MkDocs, adding multilingual client-side search with [lunr](https://lunrjs.com/) and [lunr-languages](https://github.com/MihaiValentin/lunr-languages). It's enabled by default, but must be re-added to mkdocs.yml when other plugins are used

We need to specify the search plugin because we have added another plugin. I'll put this together with a PR for another ticket.

**Comment by ccarouge** [comment] 2022-09-20 01:10
Closed by #67

**Closed by ccarouge** 2022-09-20 01:10 UTC
